### ISSUE TITLE
Forge splash screen interrupts BLS's splash screen

### ISSUE THREAD

**Issue by DenizUgur** [AlexIIL/CustomLoadingScreen#33]
When loader status says "Minecraft Engine starting" I think it's after Phase 1, another splash screen shows up for a few seconds. This could be a config conflict but I thought it would be great to create a issue for this

**Comment by AlexIIL** [comment]
I don't properly disable forge's loading screen so it could be that, however I would need to look at it properly

**Comment by DenizUgur** [comment]
Thanks man

**Comment by Tsyklop** [comment]
@DenizUgur  Forge splash screen disable in splash.properties in config folder
